/**
 * FR-API-8: writes docs/openapi.yaml from the shared zod schemas and route table.
 * With --check, fails if the committed file is out of date (used in CI).
 *
 *   pnpm openapi          # regenerate
 *   pnpm openapi:check    # verify
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { stringify } from 'yaml';
import { generateOpenApiDocument } from '@etp/shared';
import { REPO_ROOT } from './lib/context.js';

const target = join(REPO_ROOT, 'docs', 'openapi.yaml');
const { version } = JSON.parse(readFileSync(join(REPO_ROOT, 'package.json'), 'utf8')) as {
  version: string;
};

const header = '# Generated by scripts/generate-openapi.ts from packages/shared. Do not edit.\n';
const content = header + stringify(generateOpenApiDocument(version), { lineWidth: 0 });

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(target, 'utf8');
  } catch {
    // Missing file counts as out of date.
  }
  if (current !== content) {
    console.error('docs/openapi.yaml is out of date. Run: pnpm openapi');
    process.exit(1);
  }
  console.log('docs/openapi.yaml is up to date');
} else {
  writeFileSync(target, content);
  console.log(`wrote ${target}`);
}
